import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# BASE_DIR is .../project/backend/translation_assistant
BASE_DIR = Path(__file__).resolve().parent.parent

# Correct pathing to find Hos-frontend at the project root
# BASE_DIR.parent is 'backend', .parent.parent is the root directory
ROOT_DIR = BASE_DIR.parent.parent
FRONTEND_DIR = os.path.join(ROOT_DIR, 'Hos-frontend', 'dist')

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-this-in-production')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'medical-ai-assistant-0gqk.onrender.com', 
    '.onrender.com', 
    'localhost', 
    '127.0.0.1', 
    '0.0.0.0'
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'translation_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'translation_assistant.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Static files configuration
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Point to the assets folder generated by Vite
STATICFILES_DIRS = []
ASSETS_DIR = os.path.join(FRONTEND_DIR, 'assets')
if os.path.exists(ASSETS_DIR):
    STATICFILES_DIRS.append(ASSETS_DIR)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# CSRF & Security
CSRF_TRUSTED_ORIGINS = [
    'https://medical-ai-assistant-0gqk.onrender.com',
    'https://*.onrender.com'
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Log errors to the Render console
DEBUG_PROPAGATE_EXCEPTIONS = True